---
title: 813 Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  work:
    title: Work
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.813-studio.com
description: 813 studio is a creative agency servicing brands within the horological
  industry on matters of branding and content production
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: 813 Studio
email: enquiries@813-studio.com
google_site_verification: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  instagram: https://www.instagram.com/813.studio/
clients:
  bbc: https://www.bbc.co.uk
  conde-nast: https://www.condenast.co.uk
  nike: https://www.nike.com
  refinery-29: https://www.refinery29.com
  the-guardian: https://www.theguardian.com
  the-new-york-times: https://www.nytimes.com
  vice: https://www.vice.com
  youtube: https://www.universalpictures.com
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: 813-studio.imgix.net